version: '3'

volumes:
    logs:
        driver: local

services:
    slim:
      build: ./
      working_dir: /var/www/html
      environment:
          docker: "true"
      ports:
        - "8000:80"
      volumes:
        - $PWD:/var/www/html
        - $PWD/src/xdebug.ini:/etc/php.d/xdebug.ini
        - $PWD/src/vhost.conf:/etc/httpd/conf.d/vhost.conf

